import 'package:flutter/material.dart';import 'package:handyman_service_appv2/core/app_export.dart';import 'package:handyman_service_appv2/presentation/categories_plumbing_select_available_handyman_two_page/categories_plumbing_select_available_handyman_two_page.dart';class CategoriesPlumbingSelectAvailableHandymanTwoTabContainerScreen extends StatefulWidget {const CategoriesPlumbingSelectAvailableHandymanTwoTabContainerScreen({Key? key}) : super(key: key);

@override CategoriesPlumbingSelectAvailableHandymanTwoTabContainerScreenState createState() =>  CategoriesPlumbingSelectAvailableHandymanTwoTabContainerScreenState();

 }

// ignore_for_file: must_be_immutable
class CategoriesPlumbingSelectAvailableHandymanTwoTabContainerScreenState extends State<CategoriesPlumbingSelectAvailableHandymanTwoTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 5, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray50, body: SizedBox(width: double.maxFinite, child: SingleChildScrollView(child: Column(children: [_buildArrowLeftStack(context), SizedBox(height: 588.v, child: TabBarView(controller: tabviewController, children: [CategoriesPlumbingSelectAvailableHandymanTwoPage(), CategoriesPlumbingSelectAvailableHandymanTwoPage(), CategoriesPlumbingSelectAvailableHandymanTwoPage(), CategoriesPlumbingSelectAvailableHandymanTwoPage(), CategoriesPlumbingSelectAvailableHandymanTwoPage()]))]))))); } 
/// Section Widget
Widget _buildArrowLeftStack(BuildContext context) { return SizedBox(height: 212.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: SizedBox(height: 131.v, width: double.maxFinite, child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgImage7, height: 131.v, width: 390.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgArrowLeftOnprimarycontainer, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.topLeft, margin: EdgeInsets.only(left: 20.h, top: 16.v), onTap: () {onTapImgArrowLeft(context);})]))), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.symmetric(horizontal: 99.h), decoration: AppDecoration.fillYellow.copyWith(borderRadius: BorderRadiusStyle.customBorderTL8), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Mike’s Plumbing Service", style: theme.textTheme.titleMedium), SizedBox(height: 4.v), Container(height: 15.v, width: 88.h, margin: EdgeInsets.only(left: 22.h), child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, tabs: [Tab(child: CustomImageView(imagePath: ImageConstant.imgFacebook, height: 15.adaptSize, width: 15.adaptSize)), Tab(child: CustomImageView(imagePath: ImageConstant.imgFacebook, height: 15.adaptSize, width: 15.adaptSize)), Tab(child: CustomImageView(imagePath: ImageConstant.imgFacebook, height: 15.adaptSize, width: 15.adaptSize)), Tab(child: CustomImageView(imagePath: ImageConstant.imgFacebook, height: 15.adaptSize, width: 15.adaptSize)), Tab(child: CustomImageView(imagePath: ImageConstant.imgSolarStarBold, height: 15.adaptSize, width: 15.adaptSize))]))]))), CustomImageView(imagePath: ImageConstant.imgFrame17, height: 86.adaptSize, width: 86.adaptSize, radius: BorderRadius.circular(8.h), alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 56.v))])); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
