import 'package:flutter/material.dart';import 'package:handyman_service_appv2/core/app_export.dart';import 'package:handyman_service_appv2/widgets/custom_elevated_button.dart';import 'package:handyman_service_appv2/widgets/custom_floating_text_field.dart';import 'package:handyman_service_appv2/presentation/categories_plumbing_select_available_handyman_three_bottomsheet/categories_plumbing_select_available_handyman_three_bottomsheet.dart';
// ignore_for_file: must_be_immutable
class CategoriesPlumbingSelectAvailableHandymanBottomsheet extends StatelessWidget {CategoriesPlumbingSelectAvailableHandymanBottomsheet({Key? key}) : super(key: key);

TextEditingController phoneNumberController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 32.v), decoration: AppDecoration.fillOnError.copyWith(borderRadius: BorderRadiusStyle.customBorderTL30), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("Confirmation", style: theme.textTheme.titleMedium)), SizedBox(height: 25.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("Service Provider", style: CustomTextStyles.labelLargeBlack900)), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("Mike’s Plumbing Service", style: CustomTextStyles.bodySmall12)), SizedBox(height: 24.v), Divider(indent: 3.h), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("Address", style: CustomTextStyles.labelLargeBlack900)), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("No 21, Apt 12. Boulevard Complex. Birmingham", style: CustomTextStyles.bodySmall12)), SizedBox(height: 24.v), Divider(indent: 3.h), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("Service", style: CustomTextStyles.labelLargeBlack900)), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("Leaking Faucet Repair.", style: CustomTextStyles.bodySmall12)), SizedBox(height: 24.v), Divider(indent: 2.h), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("Date", style: CustomTextStyles.labelLargeBlack900)), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("18 October, 2023, 09:00AM", style: CustomTextStyles.bodySmall12)), SizedBox(height: 24.v), Divider(indent: 1.h), SizedBox(height: 23.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("Payment Method", style: CustomTextStyles.labelLargeBlack900)), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 20.h), child: Text("Cash", style: CustomTextStyles.bodySmall12)), SizedBox(height: 25.v), Divider(), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 2.h), child: CustomFloatingTextField(controller: phoneNumberController, labelText: "Your Phone Number", labelStyle: CustomTextStyles.bodySmall12, hintText: "Your Phone Number", hintStyle: CustomTextStyles.bodySmall12, textInputAction: TextInputAction.done, textInputType: TextInputType.phone)), SizedBox(height: 31.v), CustomElevatedButton(text: "Continue", margin: EdgeInsets.only(left: 2.h), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.titleMediumOnError, onPressed: () {onTapContinue(context);})])); } 

/// Shows a modal bottom sheet with [CategoriesPlumbingSelectAvailableHandymanThreeBottomsheet] 
/// widget content.
/// The sheet is displayed on top of the current view with scrolling enabled if 
/// content exceeds viewport height.
onTapContinue(BuildContext context) { showModalBottomSheet(context: context, builder: (_)=>CategoriesPlumbingSelectAvailableHandymanThreeBottomsheet(),isScrollControlled: true); } 
 }
