import '../home_page/widgets/kitchenplumbingrepairlist1_item_widget.dart';import '../home_page/widgets/kitchenplumbingrepairlist_item_widget.dart';import '../home_page/widgets/plumbingrowlist_item_widget.dart';import 'package:flutter/material.dart';import 'package:handyman_service_appv2/core/app_export.dart';import 'package:handyman_service_appv2/widgets/custom_outlined_button.dart';import 'package:handyman_service_appv2/widgets/custom_search_view.dart';
// ignore_for_file: must_be_immutable
class HomePage extends StatelessWidget {HomePage({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray5001, resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 13.v), decoration: AppDecoration.fillGray5001, child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 24.h, bottom: 5.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildLocationRow(context), SizedBox(height: 13.v), _buildWelcomePanel(context), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(right: 24.h), child: _buildJustForYou(context, justForYouText: "Categories", seeMoreText: "See more")), SizedBox(height: 11.v), _buildPlumbingRowList(context), SizedBox(height: 25.v), Padding(padding: EdgeInsets.only(right: 24.h), child: _buildJustForYou(context, justForYouText: "Just for You", seeMoreText: "See more")), SizedBox(height: 19.v), _buildKitchenPlumbingRepairList(context), SizedBox(height: 26.v), Padding(padding: EdgeInsets.only(right: 24.h), child: _buildJustForYou(context, justForYouText: "Emergency Services", seeMoreText: "See more")), SizedBox(height: 20.v), _buildKitchenPlumbingRepairList1(context)])))))); } 
/// Section Widget
Widget _buildLocationRow(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 54.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLocation, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 3.v)), Expanded(child: CustomOutlinedButton(text: "No 21, Apt 12. Boulevard Complex. Birmingham", margin: EdgeInsets.only(left: 6.h)))])); } 
/// Section Widget
Widget _buildWelcomePanel(BuildContext context) { return Card(clipBehavior: Clip.antiAlias, elevation: 0, color: theme.colorScheme.onPrimaryContainer, shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(height: 120.v, width: 342.h, decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Stack(alignment: Alignment.centerRight, children: [Opacity(opacity: 0.1, child: CustomImageView(imagePath: ImageConstant.imgRectangle7, height: 120.v, width: 77.h, radius: BorderRadius.circular(38.h), alignment: Alignment.centerLeft)), Opacity(opacity: 0.2, child: CustomImageView(imagePath: ImageConstant.imgRectangle14, height: 120.v, width: 88.h, radius: BorderRadius.circular(30.h), alignment: Alignment.centerRight)), Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Hey 👋, Motun ", style: CustomTextStyles.labelLargeOnErrorMedium), SizedBox(height: 2.v), Text("Need help finding something?", style: CustomTextStyles.bodySmallOnError), SizedBox(height: 13.v), CustomSearchView(controller: searchController, hintText: "Search for services")])))]))); } 
/// Section Widget
Widget _buildPlumbingRowList(BuildContext context) { return SizedBox(height: 60.v, child: ListView.separated(padding: EdgeInsets.only(right: 54.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 12.h);}, itemCount: 3, itemBuilder: (context, index) {return PlumbingrowlistItemWidget(onTapPlumbingRow: () {onTapPlumbingRow(context);}, onTapNext: () {onTapNext(context);});})); } 
/// Section Widget
Widget _buildKitchenPlumbingRepairList(BuildContext context) { return SizedBox(height: 170.v, child: ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 17.h);}, itemCount: 3, itemBuilder: (context, index) {return KitchenplumbingrepairlistItemWidget();})); } 
/// Section Widget
Widget _buildKitchenPlumbingRepairList1(BuildContext context) { return SizedBox(height: 170.v, child: ListView.separated(scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 17.h);}, itemCount: 3, itemBuilder: (context, index) {return Kitchenplumbingrepairlist1ItemWidget();})); } 
/// Common widget
Widget _buildJustForYou(BuildContext context, {required String justForYouText, required String seeMoreText, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(justForYouText, style: theme.textTheme.labelLarge!.copyWith(color: theme.colorScheme.onPrimaryContainer)), Container(width: 55.h, padding: EdgeInsets.symmetric(horizontal: 5.h, vertical: 1.v), decoration: AppDecoration.fillYellowA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Text(seeMoreText, style: theme.textTheme.bodySmall!.copyWith(color: theme.colorScheme.onPrimaryContainer)))]); } 

onTapPlumbingRow(BuildContext context) { // TODO: implement Actions
 } 
/// Navigates to the categoriesPlumbingScreen when the action is triggered.
onTapNext(BuildContext context) { Navigator.pushNamed(context, AppRoutes.categoriesPlumbingScreen); } 
 }
