import 'package:flutter/material.dart';import 'package:handyman_service_appv2/core/app_export.dart';import 'package:handyman_service_appv2/presentation/home_page/home_page.dart';import 'package:handyman_service_appv2/presentation/messages_chat_page/messages_chat_page.dart';import 'package:handyman_service_appv2/presentation/profile_page/profile_page.dart';import 'package:handyman_service_appv2/widgets/app_bar/appbar_leading_image.dart';import 'package:handyman_service_appv2/widgets/app_bar/appbar_title.dart';import 'package:handyman_service_appv2/widgets/app_bar/custom_app_bar.dart';import 'package:handyman_service_appv2/widgets/custom_bottom_bar.dart';
// ignore_for_file: must_be_immutable
class PrivacyPolicyScreen extends StatelessWidget {PrivacyPolicyScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray5001, body: SizedBox(width: double.maxFinite, child: Column(children: [_buildFrame(context), SizedBox(height: 16.v), Container(width: 354.h, margin: EdgeInsets.only(left: 16.h, right: 19.h), child: Text("This Privacy Policy is brought by Iqonic Design. \nIqonic Design is the sole owner of a number of demo websites containing previews of WordPress website themes. This Privacy Policy shall apply to all Iqonic Design sites where this Privacy Policy is featured. This Privacy Policy describes how the Iqonic Design collects, uses, shares and secures personal information that you provide.\n\nIqonic Design does not share personal information of any kind with anyone. We will not sell or rent your name or personal information to any third party. We do not sell, rent or provide outside access to our mailing list or any data we store. Any data that a user stores via our facilities is wholly owned by that user or business. At any time, a user or business is free to take their data and leave, or to simply delete their data from our facilities.\n\nIqonic Design may release personal information if Iqonic Design is required to by law, search warrant, subpoena, court order or fraud investigation. We may also use personal information in a manner that does not identify you specifically nor allow you to be contacted but does identify certain criteria about our site's users in general (such as we may inform third parties about the number of registered users, number of unique visitors, and the pages most frequently browsed).", maxLines: 28, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumBlack900.copyWith(height: 1.29)))])), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: _buildBottomBar(context)))); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(padding: EdgeInsets.symmetric(vertical: 18.v), decoration: AppDecoration.fillPrimary, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 8.v), CustomAppBar(height: 24.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimarycontainer, margin: EdgeInsets.only(left: 24.h), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitle(text: "Privacy Policy"))])); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Bookings: return AppRoutes.messagesChatPage; case BottomBarEnum.Cart: return "/"; case BottomBarEnum.Profile: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); case AppRoutes.messagesChatPage: return MessagesChatPage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
