import 'package:flutter/material.dart';import 'package:handyman_service_appv2/core/app_export.dart';import 'package:handyman_service_appv2/presentation/home_page/home_page.dart';import 'package:handyman_service_appv2/presentation/messages_chat_page/messages_chat_page.dart';import 'package:handyman_service_appv2/presentation/profile_page/profile_page.dart';import 'package:handyman_service_appv2/widgets/app_bar/appbar_subtitle.dart';import 'package:handyman_service_appv2/widgets/app_bar/appbar_subtitle_three.dart';import 'package:handyman_service_appv2/widgets/app_bar/appbar_title_image.dart';import 'package:handyman_service_appv2/widgets/app_bar/appbar_title_image_one.dart';import 'package:handyman_service_appv2/widgets/app_bar/custom_app_bar.dart';import 'package:handyman_service_appv2/widgets/custom_bottom_bar.dart';import 'package:handyman_service_appv2/widgets/custom_elevated_button.dart';import 'package:handyman_service_appv2/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class MessagesChatOneScreen extends StatelessWidget {MessagesChatOneScreen({Key? key}) : super(key: key);

TextEditingController descriptionController = TextEditingController();

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 26.v), child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(left: 1.h, right: 10.h), child: CustomTextFormField(controller: descriptionController, hintText: "Hey Wade, I’m on the way to your home, Please\nwait a moment. Thanks!", hintStyle: CustomTextStyles.bodyMediumGray90002, textInputAction: TextInputAction.done, maxLines: 2, contentPadding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 6.v), borderDecoration: TextFormFieldStyleHelper.fillYellow, fillColor: appTheme.yellow100)), SizedBox(height: 12.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 1.h), child: Text("4:26 Am", style: CustomTextStyles.labelLargeAvenirGray90002))), SizedBox(height: 19.v), CustomElevatedButton(height: 53.v, text: "Thank You! I’ll be waiting for that", margin: EdgeInsets.only(left: 105.h), buttonStyle: CustomButtonStyles.fillOnPrimaryContainer, buttonTextStyle: CustomTextStyles.bodyMediumOnError), SizedBox(height: 12.v), Text("5:22 Am", style: CustomTextStyles.labelLargeAvenirErrorContainer), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(centerTitle: true, title: Column(children: [Padding(padding: EdgeInsets.only(right: 24.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(top: 3.v, bottom: 18.v), onTap: () {onTapArrowLeft(context);}), AppbarTitleImageOne(imagePath: ImageConstant.imgFrame17, margin: EdgeInsets.only(left: 37.h)), Padding(padding: EdgeInsets.only(left: 13.h, top: 3.v, bottom: 3.v), child: Column(children: [AppbarSubtitle(text: "Mike Wardel"), Padding(padding: EdgeInsets.only(right: 54.h), child: Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgStar), AppbarSubtitleThree(text: "4.8", margin: EdgeInsets.only(left: 4.h))]))])), AppbarTitleImage(imagePath: ImageConstant.imgCall, margin: EdgeInsets.only(left: 64.h, top: 11.v, bottom: 10.v), onTap: () {onTapCall(context);}), AppbarTitleImage(imagePath: ImageConstant.imgOverflowMenu, margin: EdgeInsets.only(left: 12.h, top: 12.v, bottom: 11.v))])), SizedBox(height: 10.v), Align(alignment: Alignment.centerLeft, child: SizedBox(width: 361.h, child: Divider(color: appTheme.gray100, indent: 3.h)))]), styleType: Style.bgFill); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Bookings: return AppRoutes.messagesChatPage; case BottomBarEnum.Cart: return "/"; case BottomBarEnum.Profile: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); case AppRoutes.messagesChatPage: return MessagesChatPage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the messagesCallScreen when the action is triggered.
onTapCall(BuildContext context) { Navigator.pushNamed(context, AppRoutes.messagesCallScreen); } 
 }
