import 'package:flutter/material.dart';import 'package:handyman_service_appv2/core/app_export.dart';import 'package:handyman_service_appv2/presentation/home_page/home_page.dart';import 'package:handyman_service_appv2/presentation/messages_chat_page/messages_chat_page.dart';import 'package:handyman_service_appv2/presentation/profile_page/profile_page.dart';import 'package:handyman_service_appv2/widgets/app_bar/appbar_leading_image.dart';import 'package:handyman_service_appv2/widgets/app_bar/appbar_subtitle_one.dart';import 'package:handyman_service_appv2/widgets/app_bar/custom_app_bar.dart';import 'package:handyman_service_appv2/widgets/custom_bottom_bar.dart';import 'package:handyman_service_appv2/widgets/custom_elevated_button.dart';import 'package:handyman_service_appv2/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class CategoriesPlumbingScreen extends StatelessWidget {CategoriesPlumbingScreen({Key? key}) : super(key: key);

TextEditingController drainCleaningvalueController = TextEditingController();

TextEditingController specifyIssuevalueController = TextEditingController();

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 25.v), child: Column(children: [_buildCategoriesPlumbingRow1(context), SizedBox(height: 14.v), _buildCategoriesPlumbingRow2(context), SizedBox(height: 14.v), _buildCategoriesPlumbingRow3(context), SizedBox(height: 5.v)])), bottomNavigationBar: Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: _buildBottomBar(context)))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 24.v, leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimarycontainer, margin: EdgeInsets.only(left: 20.h), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "Plumbing")); } 
/// Section Widget
Widget _buildCategoriesPlumbingRow1(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 7.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 18.v), decoration: AppDecoration.fillYellowA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), SizedBox(width: 102.h, child: Text("Leaky Faucet\nRepair", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumOnPrimaryContainerMedium))]))), Expanded(child: CustomElevatedButton(height: 80.v, text: "Pipe installation\nand repair", margin: EdgeInsets.only(left: 7.h), buttonStyle: CustomButtonStyles.fillYellowATL8, buttonTextStyle: CustomTextStyles.titleMediumOnPrimaryContainerMedium, onPressed: () {onTapNext(context);}))]); } 
/// Section Widget
Widget _buildCategoriesPlumbingRow2(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 7.h), child: CustomTextFormField(controller: drainCleaningvalueController, hintText: "Drain Cleaning", contentPadding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 30.v), borderDecoration: TextFormFieldStyleHelper.fillYellowA, fillColor: appTheme.yellowA400.withOpacity(0.5)))), Container(margin: EdgeInsets.only(left: 7.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 19.v), decoration: AppDecoration.fillYellowA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: SizedBox(width: 125.h, child: Text("Toilet repair and\ninstallation", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumOnPrimaryContainerMedium)))]); } 
/// Section Widget
Widget _buildCategoriesPlumbingRow3(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 20.v), decoration: AppDecoration.fillYellowA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: SizedBox(width: 103.h, child: Text("Water Heater\nInstallation", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumOnPrimaryContainerMedium))), Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.all(0), shape: RoundedRectangleBorder(borderRadius: BorderRadiusStyle.roundedBorder8), child: Container(height: 80.v, width: 164.h, decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder8), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEdit, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 11.h)), CustomTextFormField(width: 164.h, controller: specifyIssuevalueController, hintText: "Specify Issue", textInputAction: TextInputAction.done, alignment: Alignment.center, contentPadding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 30.v), borderDecoration: TextFormFieldStyleHelper.fillGray, fillColor: appTheme.gray50001)])))]); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Home: return AppRoutes.homePage; case BottomBarEnum.Bookings: return AppRoutes.messagesChatPage; case BottomBarEnum.Cart: return "/"; case BottomBarEnum.Profile: return AppRoutes.profilePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(String currentRoute) { switch (currentRoute) {case AppRoutes.homePage: return HomePage(); case AppRoutes.messagesChatPage: return MessagesChatPage(); case AppRoutes.profilePage: return ProfilePage(); default: return DefaultWidget();} } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the categoriesPlumbingSelectAvailableHandymanTwoTabContainerScreen when the action is triggered.
onTapNext(BuildContext context) { Navigator.pushNamed(context, AppRoutes.categoriesPlumbingSelectAvailableHandymanTwoTabContainerScreen); } 
 }
