import 'package:flutter/material.dart';import 'package:handyman_service_appv2/core/app_export.dart';import 'package:handyman_service_appv2/widgets/custom_elevated_button.dart';import 'package:smooth_page_indicator/smooth_page_indicator.dart';class OnboardingScreenFourScreen extends StatelessWidget {const OnboardingScreenFourScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(extendBody: true, extendBodyBehindAppBar: true, backgroundColor: appTheme.gray900, body: Container(width: mediaQueryData.size.width, height: mediaQueryData.size.height, decoration: BoxDecoration(color: appTheme.gray900, image: DecorationImage(image: AssetImage(ImageConstant.imgOnboardingScreen), fit: BoxFit.cover)), child: SizedBox(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgFix, height: 30.v, width: 49.h, onTap: () {onTapImgFix(context);}), SizedBox(height: 37.v), Container(decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder30), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 38.v), CustomImageView(imagePath: ImageConstant.imgImage3, height: 414.v, width: 390.h)])), SizedBox(height: 18.v), Container(width: 303.h, margin: EdgeInsets.symmetric(horizontal: 43.h), child: Text("Lorem ipsum dolor sit amet consectetur. Fringilla egestas ornare volutpat.", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyLarge)), SizedBox(height: 85.v), _buildOnboardingRow(context)]))))); } 
/// Section Widget
Widget _buildOnboardingRow(BuildContext context) { return Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(left: 41.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 8.v, margin: EdgeInsets.only(top: 17.v, bottom: 14.v), child: AnimatedSmoothIndicator(activeIndex: 0, count: 4, effect: ScrollingDotsEffect(spacing: 3, activeDotColor: theme.colorScheme.primary, dotColor: appTheme.gray10001, activeDotScale: 1.3333333333333333, dotHeight: 6.v, dotWidth: 12.h))), CustomElevatedButton(height: 39.v, width: 120.h, text: "Get Started", buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.bodyLargeBlack900, onPressed: () {onTapGetStarted(context);})]))); } 
/// Navigates to the onboardingScreenOneScreen when the action is triggered.
onTapImgFix(BuildContext context) { Navigator.pushNamed(context, AppRoutes.onboardingScreenOneScreen); } 
/// Navigates to the loginFirstTimeUserScreen when the action is triggered.
onTapGetStarted(BuildContext context) { Navigator.pushNamed(context, AppRoutes.loginFirstTimeUserScreen); } 
 }
