import 'package:flutter/material.dart';import 'package:handyman_service_appv2/core/app_export.dart';import 'package:handyman_service_appv2/widgets/custom_icon_button.dart';class MessagesCallScreen extends StatelessWidget {const MessagesCallScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 16.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgArrowLeftOnprimarycontainer, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.centerLeft, onTap: () {onTapImgArrowLeft(context);}), SizedBox(height: 85.v), CustomImageView(imagePath: ImageConstant.imgFrame17, height: 86.adaptSize, width: 86.adaptSize, radius: BorderRadius.circular(8.h)), SizedBox(height: 10.v), Text("Mike Wardel", style: theme.textTheme.titleMedium), SizedBox(height: 16.v), Text("Calling...", style: CustomTextStyles.bodySmallBlack90012), SizedBox(height: 85.v), Padding(padding: EdgeInsets.symmetric(horizontal: 50.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(10.h), child: CustomImageView(imagePath: ImageConstant.imgFluentSpeaker232Filled)), Spacer(flex: 50), CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(10.h), child: CustomImageView(imagePath: ImageConstant.imgBiMicFill)), Spacer(flex: 50), CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(10.h), child: CustomImageView(imagePath: ImageConstant.imgFrame162515))])), Spacer(flex: 34), GestureDetector(onTap: () {onTapHangUp(context);}, child: Container(height: 75.adaptSize, width: 75.adaptSize, padding: EdgeInsets.all(18.h), decoration: AppDecoration.fillRedA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgIcomoonFreePhoneHangUp, height: 39.adaptSize, width: 39.adaptSize, alignment: Alignment.center))), Spacer(flex: 66)])))); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the categoriesPlumbingSelectAvailableHandymanTwoTabContainerScreen when the action is triggered.
onTapHangUp(BuildContext context) { Navigator.pushNamed(context, AppRoutes.categoriesPlumbingSelectAvailableHandymanTwoTabContainerScreen); } 
 }
